name: "Test coverage enhancement"
description: "File test coverage enhancement"
title: "[Coverage]: "
labels: ["coverage"]
body:
  - type: textarea
    attributes:
      label: Description
      placeholder: "How this feature enhances berg TS?"
  - type: dropdown
    attributes:
      label: Affects
      multiple: false
      options:
        - "configuration"
        - "runtime"
        - "deployment"
  - type: dropdown
    attributes:
      label: Subsystem
      multiple: false
      options:
        - "batch"
        - "datasource"
        - "deploymentscanner"
        - "discovery"
        - "distributable-web"
        - "ee"
        - "ejb"
        - "elytron"
        - "elytron-oidc-client"
        - "health"
        - "iiop"
        - "infinispan"
        - "interface"
        - "io"
        - "jaxrs"
        - "jca"
        - "jgroups"
        - "jmx"
        - "jpa"
        - "jsf"
        - "logging"
        - "mail"
        - "management"
        - "metrics"
        - "messaging"
        - "microprofile-config"
        - "microprofile-jwt-smallrye"
        - "modcluster"
        - "naming"
        - "paths"
        - "remoting"
        - "request-controller"
        - "resource-dapters"
        - "singleton"
        - "securitymanager"
        - "socketbinding"
        - "transaction"
        - "undertow"
        - "web-services"
        - "weld"
        - "unknown"
