name: On PR
on:
  pull_request:
    types: [opened, synchronize, edited]
jobs:
  verify-codebase:
    permissions:
      contents: write
    name: "Verify codebase"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout project"
        uses: actions/checkout@v3
      - name: "Setup NodeJS"
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: "Setup JDK"
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "17"
      - run: npm install
      - run: npm run compile
      - run: npm run lint
      - run: npm run format
      - name: Fetch last 2 commits
        uses: actions/checkout@master
        with:
          # Fetch the last 2 commits instead of just 1. (Fetching just 1 commit would overwrite the whole history)
          fetch-depth: 2
      - name: Get last commit message
        id: last-commit-message
        run: |
          echo "msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
      - name: Auto commit after format
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ steps.last-commit-message.outputs.msg }}
          commit_options: "--amend --no-edit"
          push_options: "--force"
          skip_fetch: true
