name: "Reusable Build Project Workflow"
on:
  workflow_call:
    inputs:
      spec:
        type: string
        required: false
        description: 'Spec to run'
jobs:
  build_project_job:
    name: "Build Project"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout project"
        uses: actions/checkout@v3
      - name: "Setup NodeJS"
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: "Setup JDK"
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "17"
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Setup firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: 'latest-esr'
      - name: "Run npm install"
        run: "npm install"
      - name: "Run compile"
        run: "npm run compile"
      - name: "Run all tests"
        if: "${{ github.event.inputs.spec == '' }}"
        run: "cd packages/testsuite && npm test"
      - name: "Run specific test"
        if: "${{ github.event.inputs.spec != '' }}"
        run: "cd packages/testsuite && npm test -- --specs=${{ inputs.spec }}"
